version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8910:80"
    working_dir: /code
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: crypto
    working_dir: /code
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code

#Commented out due to not being necessary for this task

#  database:
#    image: postgres:${POSTGRES_VERSION:-15}-alpine
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-app}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#      POSTGRES_USER: ${POSTGRES_USER:-app}
